import 'package:flutter/material.dart';
import '../../theme/app_colors.dart';
import '../../theme/app_theme.dart';
import '../../widgets/glass_card.dart';
import '../../widgets/eyebrow.dart';
import '../../widgets/note_box.dart';
import '../../widgets/niu_button.dart';
import '../../services/test_management_service.dart';
import '../../services/admin_service.dart';
import '../../models/test_model.dart';

class CreateTestScreen extends StatefulWidget {
  const CreateTestScreen({super.key});

  @override
  State<CreateTestScreen> createState() => _CreateTestScreenState();
}

class _CreateTestScreenState extends State<CreateTestScreen> {
  final _testMgmtService = TestManagementService();
  final _adminService = AdminService();

  List<String> _allowedCourses = [];
  bool _isLoadingCourses = true;
  bool _isSaving = false;
  String? _error;

  final _titleController = TextEditingController();
  final _qCountController = TextEditingController();
  final _durationController = TextEditingController(text: '60');
  final _marksController = TextEditingController(text: '1.0');
  final _negMarksController = TextEditingController(text: '0.0');
  final _secondsController = TextEditingController(text: '60');

  String? _selectedCourse;
  bool _negativeMarking = false;
  bool _showResults = false;
  bool _allowEditResults = false;
  bool _allowViewResults = false;

  @override
  void initState() {
    super.initState();
    _fetchCourses();
  }

  Future<void> _fetchCourses() async {
    try {
      final courses = await _adminService.getMyAllowedCourses();
      setState(() {
        _allowedCourses = courses.contains('*') ? _allCourses : courses;
        if (_allowedCourses.isNotEmpty) {
          _selectedCourse = _allowedCourses.first;
        }
        _isLoadingCourses = false;
      });
    } catch (e) {
      setState(() {
        _error = 'Failed to load courses';
        _isLoadingCourses = false;
      });
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _qCountController.dispose();
    _durationController.dispose();
    _marksController.dispose();
    _negMarksController.dispose();
    _secondsController.dispose();
    super.dispose();
  }

  Future<void> _saveTest() async {
    if (_titleController.text.trim().isEmpty) {
      setState(() => _error = 'Please enter a test title.');
      return;
    }
    if (_selectedCourse == null) {
      setState(() => _error = 'Please select a course.');
      return;
    }
    final qCount = int.tryParse(_qCountController.text) ?? 0;
    if (qCount <= 0) {
      setState(() => _error = 'Please enter a valid question count.');
      return;
    }
    final duration = int.tryParse(_durationController.text) ?? 60;
    final marks = double.tryParse(_marksController.text) ?? 1.0;
    final negMarks = double.tryParse(_negMarksController.text) ?? 0.0;
    final seconds = int.tryParse(_secondsController.text) ?? 60;

    setState(() {
      _isSaving = true;
      _error = null;
    });

    try {
      final test = TestModel(
        id: '', // Will be generated by Firestore
        title: _titleController.text.trim(),
        course: _selectedCourse!,
        questionCount: qCount,
        durationMinutes: duration,
        marksPerQuestion: marks,
        negativeMarking: _negativeMarking,
        negativeMarksPerWrong: negMarks,
        isPublished: false, // Always create as Draft
        showResults: _showResults,
        allowEditResults: _allowEditResults,
        allowViewResults: _allowViewResults,
        secondsPerQuestion: seconds,
      );

      await _testMgmtService.createTest(test);
      if (mounted) {
        Navigator.pop(context, true); // Return true to trigger refresh
      }
    } catch (e) {
      setState(() {
        _error = 'Failed to create test. Please try again.';
        _isSaving = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final topPad = MediaQuery.of(context).padding.top;

    return Scaffold(
      backgroundColor: AppColors.bgBase,
      body: SafeArea(
        child: SingleChildScrollView(
          padding: EdgeInsets.fromLTRB(22, topPad > 0 ? 12 : 24, 22, 32),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              GestureDetector(
                onTap: () => Navigator.pop(context),
                child: Container(
                  width: 36,
                  height: 36,
                  decoration: BoxDecoration(
                    color: AppColors.bone,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: const Icon(Icons.arrow_back, size: 18, color: AppColors.ink3),
                ),
              ),
              const SizedBox(height: 16),
              const Eyebrow('authoring'),
              const SizedBox(height: 4),
              Text.rich(
                TextSpan(
                  text: 'Create new ',
                  style: AppTheme.display(size: 26),
                  children: [AppTheme.italicSpan('test.')],
                ),
              ),
              const SizedBox(height: 6),
              Text(
                'Configure test settings. The test will be saved as a Draft.',
                style: AppTheme.body(size: 12.5, color: AppColors.ink4),
              ),
              const SizedBox(height: 24),

              if (_error != null)
                Padding(
                  padding: const EdgeInsets.only(bottom: 16),
                  child: NoteBox.clay(icon: Icons.error_outline, body: _error!),
                ),

              const NoteBox.gold(
                icon: Icons.info_outline,
                body: 'Must match questions seeded/authored for this course before publishing.',
              ),
              const SizedBox(height: 24),

              if (_isLoadingCourses)
                const Center(child: CircularProgressIndicator())
              else ...[
                GlassCard(
                  padding: const EdgeInsets.all(18),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      _buildTextField(
                        label: 'Test Title',
                        controller: _titleController,
                        hint: 'e.g. Midterm Examination',
                      ),
                      const SizedBox(height: 16),
                      Text(
                        'Course',
                        style: AppTheme.body(size: 12.5, color: AppColors.ink, weight: FontWeight.w500),
                      ),
                      const SizedBox(height: 6),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 12),
                        decoration: BoxDecoration(
                          border: Border.all(color: AppColors.line),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: DropdownButtonHideUnderline(
                          child: DropdownButton<String>(
                            value: _selectedCourse,
                            isExpanded: true,
                            dropdownColor: AppColors.bgBase,
                            style: AppTheme.body(size: 14, color: AppColors.ink),
                            items: _allowedCourses.map((c) {
                              return DropdownMenuItem(
                                value: c,
                                child: Text(_courseDisplayLabels[c] ?? c),
                              );
                            }).toList(),
                            onChanged: (val) {
                              if (val != null) setState(() => _selectedCourse = val);
                            },
                          ),
                        ),
                      ),
                      const SizedBox(height: 16),
                      _buildTextField(
                        label: 'Total Questions',
                        controller: _qCountController,
                        hint: '0',
                        isNumber: true,
                      ),
                      const SizedBox(height: 16),
                      _buildTextField(
                        label: 'Total Duration (Minutes)',
                        controller: _durationController,
                        isNumber: true,
                      ),
                      const SizedBox(height: 16),
                      _buildTextField(
                        label: 'Seconds Per Question (MCQ)',
                        controller: _secondsController,
                        isNumber: true,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16),
                GlassCard(
                  padding: const EdgeInsets.all(18),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Eyebrow('scoring'),
                      const SizedBox(height: 16),
                      _buildTextField(
                        label: 'Marks Per Question',
                        controller: _marksController,
                        isNumber: true,
                      ),
                      const SizedBox(height: 16),
                      _ToggleRow(
                        label: 'Negative Marking',
                        description: 'Deduct marks for wrong MCQ answers',
                        value: _negativeMarking,
                        onToggle: () => setState(() => _negativeMarking = !_negativeMarking),
                      ),
                      if (_negativeMarking) ...[
                        const SizedBox(height: 16),
                        _buildTextField(
                          label: 'Negative Marks Per Wrong Answer',
                          controller: _negMarksController,
                          isNumber: true,
                        ),
                      ],
                    ],
                  ),
                ),
                const SizedBox(height: 16),
                GlassCard(
                  padding: const EdgeInsets.all(18),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Eyebrow('permissions'),
                      const SizedBox(height: 16),
                      _ToggleRow(
                        label: 'Student View Results',
                        description: 'Students see scores after submission',
                        value: _showResults,
                        onToggle: () => setState(() => _showResults = !_showResults),
                      ),
                      const Divider(height: 24, color: AppColors.line2),
                      _ToggleRow(
                        label: 'Admin Edit Results',
                        description: 'Admins can edit results',
                        value: _allowEditResults,
                        onToggle: () => setState(() => _allowEditResults = !_allowEditResults),
                      ),
                      const Divider(height: 24, color: AppColors.line2),
                      _ToggleRow(
                        label: 'Admin View Results',
                        description: 'Admins can view results',
                        value: _allowViewResults,
                        onToggle: () => setState(() => _allowViewResults = !_allowViewResults),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
                _isSaving
                    ? const Center(child: CircularProgressIndicator())
                    : NiuButton(
                        label: 'Create Test',
                        fullWidth: true,
                        onTap: _saveTest,
                      ),
              ],
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField({
    required String label,
    required TextEditingController controller,
    String? hint,
    bool isNumber = false,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: AppTheme.body(size: 12.5, color: AppColors.ink, weight: FontWeight.w500),
        ),
        const SizedBox(height: 6),
        TextField(
          controller: controller,
          keyboardType: isNumber ? const TextInputType.numberWithOptions(decimal: true) : TextInputType.text,
          style: isNumber
              ? AppTheme.mono(size: 14, color: AppColors.ink)
              : AppTheme.body(size: 14, color: AppColors.ink),
          cursorColor: AppColors.forest,
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: AppTheme.body(size: 14, color: AppColors.ink4),
            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
            isDense: true,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: AppColors.line),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: AppColors.forest),
            ),
          ),
        ),
      ],
    );
  }
}

class _ToggleRow extends StatelessWidget {
  final String label;
  final String description;
  final bool value;
  final VoidCallback onToggle;

  const _ToggleRow({
    required this.label,
    required this.description,
    required this.value,
    required this.onToggle,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                label,
                style: AppTheme.body(size: 12.5, color: AppColors.ink, weight: FontWeight.w500),
              ),
              const SizedBox(height: 1),
              Text(
                description,
                style: AppTheme.body(size: 10.5, color: AppColors.ink4),
              ),
            ],
          ),
        ),
        GestureDetector(
          onTap: onToggle,
          child: AnimatedContainer(
            duration: const Duration(milliseconds: 200),
            width: 44,
            height: 24,
            decoration: BoxDecoration(
              color: value ? AppColors.forest : AppColors.line,
              borderRadius: BorderRadius.circular(12),
            ),
            child: AnimatedAlign(
              duration: const Duration(milliseconds: 200),
              alignment: value ? Alignment.centerRight : Alignment.centerLeft,
              child: Container(
                width: 20,
                height: 20,
                margin: const EdgeInsets.symmetric(horizontal: 2),
                decoration: const BoxDecoration(
                  color: Colors.white,
                  shape: BoxShape.circle,
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

// Full list of courses as fallback for wildcard admin.
const _allCourses = [
  'soahs_ug', 'soahs_pg', 'son_bsc', 'son_gnm', 'set_ug', 'set_pg',
  'sbm_ug', 'sbm_pg', 'solla_ug', 'solla_pg', 'sjmc', 'sos_ug',
  'sos_pg', 'sola', 'sofad', 'soe', 'sop'
];

const _courseDisplayLabels = {
  'soahs_ug': 'SOAHS UG',
  'soahs_pg': 'SOAHS PG',
  'son': 'Nursing',
  'son_bsc': 'Nursing B.Sc',
  'son_gnm': 'Nursing GNM',
  'set_ug': 'Engineering UG',
  'set_pg': 'Engineering PG',
  'sbm_ug': 'Business UG',
  'sbm_pg': 'Business PG',
  'solla_ug': 'Law UG',
  'solla_pg': 'Law PG',
  'sjmc': 'Journalism',
  'sos_ug': 'Science UG',
  'sos_pg': 'Science PG',
  'sola': 'Liberal Arts',
  'soe': 'Education',
  'sop': 'Pharmacy',
};
